# Generated by Django 4.0.2 on 2022-02-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisionApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='sample_data',
        ),
    ]
